# Generated by Django 2.1.7 on 2019-03-12 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='created_time',
            field=models.DateTimeField(auto_now=True, verbose_name='最后修改日期'),
        ),
    ]
